###
GET http://localhost:3000/projects

###
GET http://localhost:3000/projects/cbb53880-a2fc-4d15-86e5-ccd2bf7ab443

###
POST http://localhost:3000/projects
Content-Type: application/json

{
    "name": "Project 1101",
    "description": "Description 1101"
}

###
PATCH http://localhost:3000/projects/0804dc4e-af35-427d-bab5-6522a1c7abeb
Content-Type: application/json

{
    "name": "Project 1 UPDATED",
    "description": "Description 1 UPDATED",
    "started_at": "2020-01-01"
}

### Start
POST http://localhost:3000/projects/2976665f-66f2-497c-9d6b-a70bcc8e0daf/start
Content-Type: application/json

{
    "started_at": "2024-01-11"
}